### ISSUE TITLE
clang warning when using MacOS Sierra

### ISSUE THREAD

**Issue by AndyRWatson** [nodejs/node-report#22]
when attempting to install on Node v6.7.0 via npm using MacOS 10.12.1 (Sierra)  I get the following compiler warning

clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

**Comment by gibfahn** [comment]
Node core issue here: https://github.com/nodejs/node/issues/8521

**Comment by rnchamberlain** [comment]
Possible work-around here: https://github.com/nodejs/nan/issues/606

**Comment by rnchamberlain** [comment]
Fix landed in github, not published in npm yet.

**Comment by JeremyIglehart** [comment]
This is all still way over my head - I'm still experiencing this.  Any ETA when this will make it to NPM?

**Comment by rnchamberlain** [comment]
Should be on npm in the next day or so. Quite a few changes have gone in and it's a new version, just need to do the project rename, see https://github.com/nodejs/nodereport/issues/35 https://github.com/nodejs/nodereport/pull/43

**Comment by JeremyIglehart** [comment]
Wow.  Amazing work has been done here.  You all work together better than most companies do!  Hat's off to everyone on this project.  It was encouraging to read through those issues.  Thank you for al the hard work you're all working on.

**Comment by richardlau** [comment]
We've decided in #56 to revert the change made by #31 and instead be consistent with Node.js and link to the same library as it does. That means that if you build with Node.js v6 you will get deprecation warnings (you will get the same deprecation warning if you build Node.js v6, see https://github.com/nodejs/node/issues/8521#issuecomment-260649919).

Node.js v7 and above have switched to using libc++, so you will not get the warnings with those.

**Comment by rnchamberlain** [comment]
Closing this as per @richardlau comment above, fixed in Node 7 and later.
